"""Review service — Protocol and MockReviewService.

Defines the ReviewService Protocol so the application depends on an
abstraction rather than a specific AI provider. MockReviewService returns
realistic fake mistakes for development and testing.
"""

from typing import Protocol, runtime_checkable

from app.schemas.review import ReviewRequest, ReviewResponse, MistakeItem, WritingScores


@runtime_checkable
class ReviewService(Protocol):
    """Protocol for writing review services."""

    def review(self, request: ReviewRequest) -> ReviewResponse:
        """Analyze writing and return structured feedback."""
        ...


def _mock_scores(mistake_count: int, word_count: int) -> WritingScores:
    """Deterministic mock scores so dev/test runs are reproducible.

    Not meant to be a realistic quality signal -- just enough variation
    (based on how many mock mistakes fired and how much was written) to
    exercise the scoring UI without calling a real AI.
    """
    grammar = max(40, 95 - mistake_count * 12)
    clarity = max(45, 90 - mistake_count * 8)
    fluency = 80 if word_count >= 20 else 60
    engagement = 70 if word_count >= 30 else 55
    return WritingScores(grammar=grammar, fluency=fluency, clarity=clarity, engagement=engagement)


class MockReviewService:
    """Returns realistic mock review results for development/testing."""

    def review(self, request: ReviewRequest) -> ReviewResponse:
        """Return mock mistakes based on simple pattern matching."""
        writing = request.writing
        mistakes: list[MistakeItem] = []

        # Simple pattern-based mock mistakes for development
        patterns = [
            {
                "search": "i ",
                "check": lambda w: " i " in f" {w.lower()} ",
                "original": "i",
                "correction": "I",
                "category": "Grammar",
                "explanation": 'The pronoun "I" should always be capitalized in English.',
            },
            {
                "search": "alot",
                "check": lambda w: "alot" in w.lower(),
                "original": "alot",
                "correction": "a lot",
                "category": "Spelling",
                "explanation": '"A lot" is always written as two words, not one.',
            },
            {
                "search": "dont",
                "check": lambda w: "dont" in w.lower() and "don't" not in w.lower(),
                "original": "dont",
                "correction": "don't",
                "category": "Punctuation",
                "explanation": "Contractions need an apostrophe: don't, can't, won't.",
            },
            {
                "search": "very",
                "check": lambda w: "very" in w.lower(),
                "original": "very",
                "correction": "(more specific word)",
                "category": "Word Choice",
                "explanation": (
                    '"Very" is often overused. Consider more specific alternatives: '
                    '"extremely," "remarkably," "particularly," or a stronger adjective.'
                ),
            },
        ]

        for pattern in patterns:
            if pattern["check"](writing):
                mistakes.append(
                    MistakeItem(
                        original=pattern["original"],
                        correction=pattern["correction"],
                        category=pattern["category"],
                        explanation=pattern["explanation"],
                    )
                )

        # Always provide general feedback
        word_count = len(writing.split()) if writing.strip() else 0
        if word_count < 20:
            summary = "Your response is quite short. Try to develop your ideas more fully."
        elif word_count < 50:
            summary = "Good start! Try to add more detail and examples to strengthen your writing."
        else:
            summary = "Good effort! You wrote a substantial response. Review the feedback below."

        if not mistakes:
            summary += " No obvious issues detected by the mock reviewer — AI review will provide deeper analysis."

        return ReviewResponse(
            mistakes=mistakes,
            summary=summary,
            overall_feedback=(
                "This feedback was generated by the mock review service. "
                "Real AI-powered review will be available in Phase 3."
            ),
            scores=_mock_scores(len(mistakes), word_count),
        )
